version: '3'

services:
  my-wallet:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: my-wallet
    volumes: 
      - .:/usr/home/app
    working_dir: /usr/home/app
    ports:
      - 3048:3048
    restart: always
    tty: true
    networks:
      - mywallet-network
    environment: 
      - CHOKIDAR_USEPOLLING=true

networks:
  mywallet-network:
    driver: bridge